### ISSUE TITLE
Release 0.9.3 on Rubygems

### ISSUE THREAD

**Issue by apolishch** [spejman/gga4r#6]
Is there an ETA for this?

The current version (0.9.2) appears to have a bug:

gga4r-0.9.2/lib/gga4r/gga4r_main.rb:114:in `block (2 levels) in evaluation_with_threads': undefined method`id' for #<Thread:0x007ff7fa04cb68 dead> (NoMethodError)

**Comment by pcarranzav** [comment]
@spejman is there any issue to solve or feature to add in order to do this?

**Comment by spejman** [comment]
@pcarranzav @apolishch I'm sorry but currently I've no time to fix this, but feel free to fix, I'll check and merge pull request and create new release for rubygems.

**Comment by pcarranzav** [comment]
@spejman  I think it's ready for release, the bug that @apolishch mentions is in a method that no longer exists.

**Comment by spejman** [comment]
@pcarranzav you're right!

@apolishch I've just released 0.9.3 version to rubygems. Sorry for the delay.
