### ISSUE TITLE
Psych dependency

### ISSUE THREAD

**Issue by pcarranzav** [spejman/gga4r#8]
Is it necessary? I removed it when developing and didn't have any trouble.
populate_from_file and save_population are now implemented with ruby's YAML module, aren't they?

**Comment by spejman** [comment]
Which version of ruby did you use?

**Comment by pcarranzav** [comment]
1.9.3

**Comment by spejman** [comment]
Removed:
https://github.com/spejman/gga4r/commit/98b7dd4f43587d989046c2948ff4a063a58d714b

Thanks!
